# Generated by Django 4.2.4 on 2023-09-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookreview_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['date']},
        ),
    ]
