# Generated by Django 4.2.4 on 2023-09-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_bookreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-date']},
        ),
    ]
