# Generated by Django 4.2.7 on 2023-12-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_book_options_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
